<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-HADT1D5" failures="2" tests="2" name="Test(failed)" time="0.077" errors="0" timestamp="2022-12-17T14:38:36 IST">
  <testcase classname="com.nxtgenai.retryfailedtestdemo.FailedTestDemo1" name="testCase1" time="0.023">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.nxtgenai.retryfailedtestdemo.FailedTestDemo1.testCase1(FailedTestDemo1.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testCase1 -->
  <testcase classname="com.nxtgenai.retryfailedtestdemo.FailedTestDemo1" name="testCase3" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.nxtgenai.retryfailedtestdemo.FailedTestDemo1.testCase3(FailedTestDemo1.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testCase3 -->
  <testcase classname="com.nxtgenai.retryfailedtestdemo.FailedTestDemo1" name="testCase2" time="0.0">
    <ignored/>
  </testcase> <!-- testCase2 -->
  <testcase classname="com.nxtgenai.retryfailedtestdemo.FailedTestDemo1" name="testCase4" time="0.0">
    <ignored/>
  </testcase> <!-- testCase4 -->
</testsuite> <!-- Test(failed) -->
